config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "entries#index"
  resources :entries

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  def index
    @selected_date = params[:date]&.to_date
    @selected_date ||= Date.today
    @current_month = @selected_date.strftime("%B")
    @entries = Entry.where("DATE(start_time) = ?", @selected_date)
    @holidays = {
      "New Year’s Day" => "January 1",
      "Chinese New Year" => "February 10",
      "Maundy Thursday" => "March 28",
      "Good Friday" => "March 29",
      "Black Saturday" => "March 30",
      "Day of Valor (Araw ng Kagitingan)" => "April 9",
      "Eid'l Fitr" => "April 10",
      "Labor Day" => "May 1",
      "Independence Day" => "June 12",
      "Ninoy Aquino Day" => "August 21",
      "National Heroes Day" => "August 26",
      "All Saints’ Day" => "November 1",
      "All Souls’ Day" => "November 2",
      "Bonifacio Day" => "November 30",
      "Feast of the Immaculate Conception of Mary" => "December 8",
      "Christmas Eve" => "December 24",
      "Christmas Day" => "December 25",
      "Rizal Day" => "December 30",
      "Last Day of the Year" => "December 31"
    }
    @holidays_in_current_month = @holidays.select { |_, date| Date.parse(date).strftime("%B") == @current_month }
    if @holidays_in_current_month.empty?
      @holidays_in_current_month["Life is too short to wait for holidays to have a good time. Embrace the ordinary moments and make them extraordinary. 🎉" ] = nil
    end
  end

  def show
  end

  def new
    @entry = Entry.new
  end

  def edit
  end

  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @entry.destroy!

    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_entry
      @entry = Entry.find(params[:id])
    end

    def entry_params
      params.require(:entry).permit(:category, :title, :description, :start_time, :end_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_display.html.erb
<main class="flex flex-col gap-6">
    <section class="flex gap-4">
            <span class="h-20 w-24 flex justify-center items-center bg-gray-300 text-5xl rounded">
              <% case @entry.category %>
                <% when "Work" %>
                    <%= fa_icon "briefcase", class: "text-blue-600 imageRotateHorizontal" %>
                <% when "Personal" %>
                    <%= fa_icon "user", class: "text-sky-600 imageRotateHorizontal" %>
                <% when "Health" %>
                    <%= fa_icon "heartbeat", class: "text-red-600 imageRotateHorizontal" %>
                <% when "Finance" %>
                    <%= fa_icon "money", class: "text-green-600 imageRotateHorizontal" %>
                <% when "Hobbies" %>
                    <%= fa_icon "paint-brush", class: "text-purple-600 imageRotateHorizontal" %>
                <% when "Goals" %>
                    <%= fa_icon "bullseye", class: "text-orange-600 imageRotateHorizontal" %>
                <% when "Notes" %>
                    <%= fa_icon "sticky-note", class: "text-yellow-800 imageRotateHorizontal" %>
                <% when "Reminders" %>
                    <%= fa_icon "bell", class: "text-pink-600 imageRotateHorizontal" %>
                <% else %>
                    <%= fa_icon "coffee", class: "text-yellow-950 imageRotateHorizontal" %>
                <% end %>
            </span>
        <div class="flex flex-col justify-center">
            <h2 class="text-sm font-semibold">
                <%= @entry.category.upcase%>
            <h2>
            <h1 class="text-2xl font-semibold pb-1">
                <%= @entry.title%>
            </h1>
            <p class="text-xs">
                <%= @entry.start_time.strftime("%H:%M %p") %> to <%= @entry.end_time.strftime("%H:%M %p")%>
            </p>
        </div>
    </section>
    <section>
        <p class="bg-white text-justify p-6 shadow-md rounded truncate">
          <%= @entry.description%>
        </p>
    </section>
</main>

app/views/entries/_entry.html.erb
<%= link_to entry_path(entry) do %>
  <div class="bg-white rounded shadow mx-4 mt-1 mb-4 group hover:scale-105 transition-all ease-in-out">
    <div class="flex p-2 gap-2">
      <section class="w-20">
        <div class="h-12 flex justify-center items-center bg-gray-200">
          <span class="text-4xl">
            <% case entry.category %>
              <% when "Work" %>
                <%= fa_icon "briefcase", class: "group-hover:text-blue-600" %>
              <% when "Personal" %>
                <%= fa_icon "user", class: "group-hover:text-sky-600" %>
              <% when "Health" %>
                <%= fa_icon "heartbeat", class: "group-hover:text-red-600" %>
              <% when "Finance" %>
                <%= fa_icon "money", class: "group-hover:text-green-600" %>
              <% when "Hobbies" %>
                <%= fa_icon "paint-brush", class: "group-hover:text-purple-600" %>
              <% when "Goals" %>
                <%= fa_icon "bullseye", class: "group-hover:text-orange-600" %>
              <% when "Notes" %>
                <%= fa_icon "sticky-note", class: "group-hover:text-yellow-800" %>
              <% when "Reminders" %>
                <%= fa_icon "bell", class: "group-hover:text-pink-600" %>
              <% else %>
                <%= fa_icon "coffee", class: "group-hover:text-yellow-950" %>
            <% end %>
          </span>
        </div>
        <div class="bg-blue-400 font-semibold text-white text-xs text-center">
          <%= entry.category.upcase %>
        </div>
      </section>
      <section class="flex flex-col justify-center">
        <h1 class="font-semibold">
          <%= entry.title %>
        </h1>
        <p class="text-xs">
          <%= entry.start_time.strftime("%H:%M %p") %> to <%= entry.end_time.strftime("%H:%M %p") %>
        </p>
        <p class="text-sm max-w-[55vw] md:max-w-[22vw] truncate">
          <%= entry.description %>
        </p>
      </section>
    </div>
  </div>
<% end %>

app/views/entries/_form.html.erb
<%= form_with(model: entry, class: "contents") do |form| %>
  <% if entry.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
        <% entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <main class="w-full flex flex-col gap-4">
    <div class="w-full flex flex-col gap-1">
      <h1>
        <%= form.label :category, class: "font-semibold" %>
      </h1>
      <span>
      <%= form.select :category, options_for_select(["Work", "Personal", "Health", "Finance", "Hobbies", "Goals", "Notes", "Reminders", "Others"]), {}, class: "w-full rounded border-none shadow" %>
      </span>
    </div>

    <div class="flex flex-col gap-1">
      <h1>
      <%= form.label :title, class: "font-semibold" %>
      </h1>
      <span>
      <%= form.text_field :title, placeholder: "Add your title", class: "w-full rounded border-none shadow" %>
      </span>
    </div>

    <div class="flex flex-col gap-1">
      <h1>
      <%= form.label :start_time, class: "font-semibold" %>
      </h1>
      <span>
      <%= form.datetime_field :start_time, class: "w-full rounded border-none shadow" %>
      </span>
    </div>

    <div class="flex flex-col gap-1">
      <h1>
      <%= form.label :end_time, class: "font-semibold" %>
      </h1>
      <span>
      <%= form.datetime_field :end_time, class: "w-full rounded border-none shadow"  %>
      </span>
    </div>

    <div>
      <%= form.label :description, class: "font-semibold" %>
      <%= form.text_area :description, placeholder: "Add your plan", rows: 4.5, class: "w-full text-justify rounded border-none shadow" %>
    </div>

    <div class="flex justify-center mt-4">
      <%= form.submit class: "bg-green-500 font-semibold text-white p-2 rounded cursor-pointer" %>
    </div>
  </main>
<% end %>

app/views/entries/_stats.html.erb
<main class="flex flex-col gap-4">
    <h1 class="text-sm text-center font-semibold">HOLIDAYS</h1>
    <ul>
    <% @holidays_in_current_month.each do |holiday, date| %>
        <li class="text-center font-bold p-2 mb-4 bg-blue-400 text-white rounded shadow cursor-pointer">
            <%= "#{date} #{holiday}" %>
        </li>
    <% end %>
    </ul>
</main>

app/views/entries/edit.html.erb
<div class="flex flex-col mx-auto md:w-2/3 gap-4 p-8">
  <section class="flex justify-between">
      <div class="text-2xl text-gray-500 hover:text-gray-800">
        <%= link_to @entry do %>
            <%= fa_icon "arrow-left"%>
        <% end %>
      </div>
      <div class="flex text-xl gap-2">
        <span class="text-gray-500 hover:text-blue-600">
            <%= link_to entries_path do %>
                <%= fa_icon "home"%>
            <% end %>
        </span>
      </div>
  </section>
  <%= render "form", entry: @entry %>
</div>

app/views/entries/index.html.erb
<div class="w-full flex flex-col px-8 gap-4 md:flex-row md:max-w-[65rem] md:mx-auto">
  <div class="w-full flex flex-col items-center justify-center p-8 gap-8">
    <div>
      <%= render "layouts/calendar"%>
    </div>
    <div class="hidden md:block  md:w-full md:h-full">
      <%= render "entries/stats"%>
    </div>
  </div>
  <div class="w-full md:py-8">
    <% content_for :title, "Entries" %>
    <div class="flex justify-between items-center mb-2">
      <h1 class="text-3xl font-semibold">Plans</h1>
      <%= link_to new_entry_path do %>
      <span class="font-semibold hover:text-blue-500 cursor-pointer">
        <%= fa_icon "plus-square" %>
        ADD
      </span>
      <% end %>
    </div>
    <div id="entries" class="h-64 overflow-scroll md:h-full">
      <% @entries.each do |entry| %>
        <%= render entry %>
      <% end %>
    </div>
  </div>
</div>

app/views/entries/new.html.erb
<div class="flex flex-col mx-auto md:w-2/3 gap-4 p-8">
  <section class="flex justify-between">
      <div class="text-2xl text-gray-500 hover:text-gray-800">
        <%= link_to @entry do %>
            <%= fa_icon "arrow-left"%>
        <% end %>
      </div>
      <div class="flex text-xl gap-2">
        <span class="text-gray-500 hover:text-blue-600">
            <%= link_to entries_path do %>
                <%= fa_icon "home"%>
            <% end %>
        </span>
      </div>
  </section>
  <%= render "form", entry: @entry %>
</div>

app/views/entries/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex flex-col p-8">
  <section class="flex justify-between">
      <div class="text-2xl text-gray-500 hover:text-gray-800">
        <%= link_to entries_path do %>
            <%= fa_icon "arrow-left"%>
        <% end %>
      </div>
      <div class="flex text-xl gap-2">
        <span class="text-gray-500 hover:text-blue-600">
            <%= link_to edit_entry_path(@entry) do %>
                <%= fa_icon "pencil"%>
            <% end %>
        </span>
        <span class="text-gray-500 hover:text-red-600">
            <%= button_to @entry, method: :delete, data: {turbo_confirm: "Are you sure?"} do %>
                <%= fa_icon "trash"%>
            <% end %>
        </span>
      </div>
    </section>
    <h1 class="text-gray-700 text-2xl text-center font-semibold my-6">
        <%= @entry.start_time.strftime("%A, %d %B %Y")%>
    </h1>
  <div class="w-full mx-auto">
    <%= render "entries/display"%>
</div>

app/views/layouts/_calendar.html.erb
<%= month_calendar do |date | %>
    <%= date.day.to_s.ljust(2) %>
<% end %>

app/views/layouts/_nav.html.erb
<div class="h-14 w-full flex items-center <%= user_signed_in? ? 'justify-between' : 'justify-center' %> px-8 bg-blue-700 md:h-24 md:max-w-2/3 md:mx-auto md:px-16 transition-all ease-in-out">
 <img class="h-12 md:h-16" src="https://i.postimg.cc/g2gQFW73/logo.png" alt="Logo" />
  <% if user_signed_in? %>
    <div class="flex gap-2 text-lg text-white md:text-2xl md:gap-4">
        <span class="cursor-pointer">
            <%= button_to destroy_user_session_path, method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "bg-transparent border-none p-0" do %>
                <%= fa_icon "sign-out" %>
            <% end %>
        </span>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>planit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="icon" type="image/svg+xml" href="https://i.postimg.cc/BZ5CL3Nm/journal-8293580.png" />
  </head>

  <body class="h-screen bg-blue-50">
    <%= render partial: "shared/notifications", locals: { message: flash[:notice]} %>
    <div class="">
      <div class="flex justify-center">
        <%= render "layouts/nav" %>
      </div>
    </div>
    <main class="w-full flex items-center justify-center">
      <%= yield %>
    </main>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.turbo.min.js"></script>
    <script>
      document.addEventListener('DOMContentLoaded', function() {
          var toast = document.getElementById('toast-success');
          if (toast) {
              setTimeout(function() {
                  toast.classList.add('hidden');
              }, 2000);
          }
      });
      document.addEventListener('DOMContentLoaded', function() {
          var toast = document.getElementById('toast-danger');
          if (toast) {
              setTimeout(function() {
                  toast.classList.add('hidden');
              }, 2000);
          }
      });
    </script>
  </body>
</html>

app/views/shared/_notifications.html.erb
<% if message %>
  <% if ["Entry was successfully updated.", "Entry was successfully created."].include?(message) %>
    <div
      id="toast-success"
      class="transition transform duration-1000 absolute bottom-5 right-5 flex items-center w-full max-w-xs p-4 mb-4 text-gray-500 bg-white rounded-lg shadow dark:text-gray-400 dark:bg-gray-800"
      role="alert"
      data-controller="notification"
      data-notification-hidden-value="true"
      data-action="awesome@window->notification#show"
      data-transition-enter-from="opacity-0 translate-x-6"
      data-transition-enter-to="opacity-100 translate-x-0"
      data-transition-leave-from="opacity-100 translate-x-0"
      data-transition-leave-to="opacity-0 translate-x-6"
    >
      <div class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 text-green-500 bg-green-100 rounded-lg dark:bg-green-800 dark:text-green-200">
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
          <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 8.207-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L9 10.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z"/>
        </svg>
        <span class="sr-only">Check icon</span>
      </div>
      <div class="ms-3 text-sm font-normal"><%= message %></div>
      <button type="button" class="ms-auto -mx-1.5 -my-1.5 bg-white text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex items-center justify-center h-8 w-8 dark:text-gray-500 dark:hover:text-white dark:bg-gray-800 dark:hover:bg-gray-700" data-dismiss-target="#toast-success" aria-label="Close">
        <span class="sr-only">Close</span>
        <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
        </svg>
      </button>
    </div>
  <% elsif message == "Entry was successfully destroyed." %>
    <div
      id="toast-danger"
      class="transition transform duration-1000 absolute bottom-5 right-5 flex items-center w-full max-w-xs p-4 mb-4 text-gray-500 bg-white rounded-lg shadow dark:text-gray-400 dark:bg-gray-800"
      role="alert"
      data-controller="notification"
      data-notification-hidden-value="true"
      data-action="awesome@window->notification#show"
      data-transition-enter-from="opacity-0 translate-x-6"
      data-transition-enter-to="opacity-100 translate-x-0"
      data-transition-leave-from="opacity-100 translate-x-0"
      data-transition-leave-to="opacity-0 translate-x-6"
    >
      <div class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 text-red-500 bg-red-100 rounded-lg dark:bg-red-800 dark:text-red-200">
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
          <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 11.793a1 1 0 1 1-1.414 1.414L10 11.414l-2.293 2.293a1 1 0 0 1-1.414-1.414L8.586 10 6.293 7.707a1 1 0 0 1 1.414-1.414L10 8.586l2.293-2.293a1 1 0 0 1 1.414 1.414L11.414 10l2.293 2.293Z"/>
        </svg>
        <span class="sr-only">Error icon</span>
      </div>
      <div class="ms-3 text-sm font-normal">Item has been deleted.</div>
      <button type="button" class="ms-auto -mx-1.5 -my-1.5 bg-white text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex items-center justify-center h-8 w-8 dark:text-gray-500 dark:hover:text-white dark:bg-gray-800 dark:hover:bg-gray-700" data-dismiss-target="#toast-danger" aria-label="Close">
        <span class="sr-only">Close</span>
        <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
        </svg>
      </button>
    </div>
  <% end %>
<% end %>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading flex justify-center">
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>

    <nav class="flex justify-center">
        <div><%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %></div>
        <div><%= link_to t('simple_calendar.today', default: 'Today'), calendar.url_for_today_view %></div>
        <div><%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %></div>
    </nav>

  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

<nav class="flex justify-between items-center px-4">
      <div class="text-xl text-gray-500 hover:text-gray-800">
        <%= link_to calendar.url_for_previous_view do %>
          <%= fa_icon "chevron-circle-left"%>
        <% end %>
      </div>
      <div>
        <%= link_to calendar.url_for_today_view do %>
          <p class="font-bold text-xs text-white bg-gray-400 px-2 hover:bg-gray-800 rounded">TODAY</p>
        <% end %>
      </div>
      <div class="text-xl text-gray-500 hover:text-gray-800">
        <%= link_to calendar.url_for_next_view do %>
          <%= fa_icon "chevron-circle-right"%>
        <% end %>
      </div>
    </nav>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <time datetime="<%= start_date.strftime('%Y-%m') %>" class="calendar-title">
    <h1 class="text-center text-2xl font-semibold tracking-tighter">
      <span>
        <%= t('date.month_names')[start_date.month] %>
      </span>
      <span>
        <%= start_date.year %>
      </span>
    </h1>
    </time>


  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th class="p-2"><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <div class="flex justify-center items-center">
                <%= link_to entries_path(date: day.strftime("%Y-%m-%d")), class: "p-2 #{'bg-blue-400 font-bold text-white rounded' if day == @selected_date}" do %>
                  <%= day.strftime("%d") %>
                <% end %>
              </div>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <span class="calendar-title">
      <%= t('simple_calendar.week', default: 'Week') %>
      <%= calendar.week_number %>
      <% if calendar.number_of_weeks > 1 %>
        - <%= calendar.end_week %>
      <% end %>
    </span>

    <nav>
      <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
      <%= link_to t('simple_calendar.today', default: 'Today'), calendar.url_for_today_view %>
      <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
    </nav>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <%= link_to day.strftime("%d"), entries_path(date: day) %>
            <% end %>
         <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>